### PR TITLE
Feature TwiML REST API Channel

### PR DESCRIPTION
**Pull request by teehamaral**
Added TwiML REST API channel with tests

### CODE REVIEW

**Comment by dwilkie** [comment]
@teehamaral there are too many commits here. Can you fork this project and only commit the changes needed for the TwiML REST API. (It looks like just the last 5 commits)

**Comment by teehamaral** [comment]
@dwilkie all these commits are related to the latest update of RapidPro, as some methods used in the version that is on your repository are currently in disuse, it may cause a refuse of your PR in the repository base. But if it is better for you, you can make your way.

**Comment by dwilkie** [comment]
Ah sorry I just saw that this PR is against Master. Can you make it against the branch https://github.com/dwilkie/rapidpro/tree/twilio_compliant_api which is up to date with the latest RapidPro. This is also the branch which has the PR against the main RapidPro, so when I pull it in it will be correct Sorry for the confusion!

**Comment by teehamaral** [comment]
Ah, all right @dwilkie. I send to the branch you were working :)

**Comment by teehamaral** [comment]
Hey @dwilkie, I think your branch is not fully up to date with the latest update of RapidPro. This alert was displayed when I tried to do the PR for the branch you are working "Can’t automatically merge. Don’t worry, you can still create the pull request."

**Comment by dwilkie** [comment]
Hey @teehamaral my branch is up to date but there are conflicts with your PR. I already did some of what you did in my branch so some your changes override my changes. I can go through the fix the conflicts.

**Comment by teehamaral** [comment]
So you prefer that I send the PR even with the conflicts that you solve them, @dwilkie?

**Comment by dwilkie** [comment]
Yes please do that and I will try to solve the conflicts. Then you can also
see what I've done on this. Very similar to what you have done just some
minor changes

**Pull request merged**
